import React, { useState, useEffect, useRef } from "react";
import Sidebar from "../components/Sidebar";
import { chatAPI } from "../services/api";

export default function ChatPage() {
  const [chatId, setChatId] = useState(null);
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const bottomRef = useRef(null);

  // Load selected conversation history
  useEffect(() => {
    if (chatId) {
      chatAPI.getConversation(chatId)
        .then((data) => {
          if (data.messages) setMessages(data.messages);
        })
        .catch((e) => console.error(e));
    } else {
      setMessages([]);
    }
  }, [chatId]);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, loading]);

  const handleSend = async () => {
    const text = input.trim();
    if (!text || loading) return;

    const userMsg = { role: "user", message: text };
    setMessages((prev) => [...prev, userMsg]);
    setInput("");
    setLoading(true);

    try {
      const res = await chatAPI.sendMessage(text, chatId);
      const botMsg = { role: "assistant", message: res.reply };
      setMessages((prev) => [...prev, botMsg]);
      
      // Update our chatId if it was just generated by the backend
      if (res.chat_id && res.chat_id !== chatId) {
        setChatId(res.chat_id);
      }
    } catch (e) {
      setMessages((prev) => [...prev, { role: "assistant", message: "Error sending message." }]);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={styles.container}>
      {/* 🔹 SIDEBAR (Shows one entry per conversation) */}
      <Sidebar onSelectChat={(id) => setChatId(id)} currentChatId={chatId} />
      
      {/* 🔹 CHAT AREA */}
      <div style={styles.chatArea}>
        <div style={styles.header}>
          <h2 style={{ margin: "0", fontSize: "18px", color: "var(--text-primary, #333)" }}>
            {chatId ? "Conversation" : "New Chat"}
          </h2>
        </div>
        
        <div style={styles.feed}>
          {messages.length === 0 && (
            <div style={styles.empty}>
              <div style={styles.emptyIcon}>💬</div>
              <p>Hello! How can I help you today?</p>
            </div>
          )}
          {messages.map((m, i) => (
            <div 
              key={i} 
              style={{
                ...styles.messageRow, 
                justifyContent: m.role === "user" ? "flex-end" : "flex-start"
              }}
            >
              <div style={{
                ...styles.bubble,
                ...(m.role === "user" ? styles.bubbleUser : styles.bubbleBot)
              }}>
                {m.message}
              </div>
            </div>
          ))}
          {loading && (
            <div style={{...styles.messageRow, justifyContent: "flex-start"}}>
              <div style={{...styles.bubble, ...styles.bubbleBot}}>...</div>
            </div>
          )}
          <div ref={bottomRef} />
        </div>

        <div style={styles.inputArea}>
          <input
            style={styles.input}
            placeholder="Type your message..."
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && handleSend()}
          />
          <button 
            style={{...styles.sendBtn, opacity: (!input.trim() || loading) ? 0.6 : 1}} 
            onClick={handleSend} 
            disabled={loading || !input.trim()}
          >
            Send
          </button>
        </div>
      </div>
    </div>
  );
}

const styles = {
  container: {
    display: "flex",
    height: "100vh",
    width: "100%",
    background: "#fff",
    fontFamily: "var(--font-body, Arial, sans-serif)",
  },
  chatArea: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    background: "var(--bg, #fff)",
  },
  header: {
    padding: "20px",
    borderBottom: "1px solid var(--border, #e5e5e5)",
    background: "var(--bg-2, #fff)",
  },
  feed: {
    flex: 1,
    padding: "20px 40px",
    display: "flex",
    flexDirection: "column",
    gap: "20px",
    overflowY: "auto",
  },
  empty: {
    margin: "auto",
    color: "var(--text-muted, #666)",
    fontSize: "16px",
    textAlign: "center",
  },
  emptyIcon: {
    fontSize: "40px",
    marginBottom: "10px",
  },
  messageRow: {
    display: "flex",
    width: "100%",
  },
  bubble: {
    maxWidth: "70%",
    padding: "14px 20px",
    borderRadius: "18px",
    fontSize: "15px",
    lineHeight: "1.5",
    whiteSpace: "pre-wrap",
  },
  bubbleUser: {
    background: "var(--teal, #007aff)",
    color: "#fff",
    borderBottomRightRadius: "4px",
  },
  bubbleBot: {
    background: "var(--bg-input, #f0f0f0)",
    color: "var(--text-primary, #000)",
    borderBottomLeftRadius: "4px",
  },
  inputArea: {
    padding: "20px 40px",
    borderTop: "1px solid var(--border, #e5e5e5)",
    display: "flex",
    gap: "10px",
    background: "var(--bg-2, #fff)",
  },
  input: {
    flex: 1,
    padding: "14px 20px",
    borderRadius: "24px",
    border: "1px solid var(--border, #ccc)",
    background: "var(--bg-input, #fff)",
    color: "var(--text-primary, #000)",
    fontSize: "15px",
    outline: "none",
  },
  sendBtn: {
    padding: "0 24px",
    borderRadius: "24px",
    background: "var(--teal, #10a37f)",
    color: "#fff",
    border: "none",
    cursor: "pointer",
    fontWeight: "bold",
    fontSize: "15px",
    transition: "opacity 0.2s",
  }
};